#!/bin/bash

SCRIPT=$(readlink -f "$0")
ROOTDIR=$(dirname $SCRIPT)

# install ansible - from https://github.com/William-Yeh/docker-ansible/blob/master/ubuntu16.04/Dockerfile
if [[ $(which ansible | wc -l) -eq 0 ]]; then
	echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu xenial main" | tee /etc/apt/sources.list.d/ansible.list           && \
	echo "deb-src http://ppa.launchpad.net/ansible/ansible/ubuntu xenial main" | tee -a /etc/apt/sources.list.d/ansible.list    && \
	apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7BB9C367    && \
	DEBIAN_FRONTEND=noninteractive  apt-get update  && \
	\
	\
	echo "===> Installing Ansible..."  && \
	apt-get install -y ansible  && \
	\
	\
	echo "===> Adding hosts for convenience..."  && \
	echo 'localhost ansible_connection=local' > /etc/ansible/hosts
fi

if [[ $(which make | wc -l) -eq 0 ]]; then
	apt-get install -y make
fi

ansible-playbook -i "localhost," --connection="local" $ROOTDIR/ansible/ns_install.yml --extra-vars "_rootdir=$ROOTDIR" -v
